name: Upload Files to GCS

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  upload-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: "project-e224783c-d3b2-4cda-bea"
          workload_identity_provider: "projects/761514383820/locations/global/workloadIdentityPools/github-terraform1/providers/github-provider"
          service_account: "github-terraform@project-e224783c-d3b2-4cda-bea.iam.gserviceaccount.com"

      - name: Upload bucket-data
        run: |
          gcloud storage cp --recursive bucket-data gs://terraform-demo-project-e224783c-d3b2/
